#pipe cat > meta/main.yml
---

galaxy_info:
  author: Thierry Delamare
  description: Install my bashrc
  company: EpiConcept
  license: MIT
  min_ansible_version: 2.3
  platforms:
  - name: Debian
    versions:
    - jessie
  categories:
  - system
dependencies: []
#pipe cat > bashrc-play.yml
#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: True

  vars:
    bashrc:
      users:
        example:            # user name
          dir: my_dot_files # user dot files folder
          template: servers # which template to use
          file: my_bashrc   # which file to generate
        thy:                # sane defaults apply

  roles:
    - .
#pipe cat > defaults/main.yml
---

bashrc_template: default
bashrc_file: bashrc
# dynamic default via task
#bashrc_dir: ~/.{{ ansible_ssh_user }}

#pipe cat > tasks/main.yml
---

- assert:
    that:
      - ansible_user_id != 'root'
      - bashrc.users[ansible_user_id] is defined

- set_fact:
    dir: ~/.{{ bashrc.users[ansible_user_id].dir | default(ansible_user_id) }}
    file: '{{ bashrc.users[ansible_user_id].file | default(bashrc_file) }}'
    template: '{{ bashrc.users[ansible_user_id].template | default(bashrc_template) }}.j2'

- set_fact:
    line: if [ -f {{ dir }}/{{ file }} ]; then . {{ dir }}/{{ file }}; fi

- name: our dot dir
  file:
    path: '{{ dir }}'
    state: directory

- name: install template
  template:
    src: '{{ template }}'
    dest: '{{ dir }}/{{ file }}'

- name: edit .bashrc
  lineinfile:
    dest: ~/.bashrc
    state: present
    insertafter: EOF
    line: '{{ line }}'
#pipe touch .stone
