#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: True

  vars:
    bashrc:
      users:
        example:            # user name
          dir: my_dot_files # user dot files folder
          template: servers # which template to use
          file: my_bashrc   # which file to generate
        thy:                # sane defaults apply

  roles:
    - .
