---

- assert:
    that:
      - ansible_user_id != 'root'
      - bashrc.users[ansible_user_id] is defined

- set_fact:
    dir: ~/.{{ bashrc.users[ansible_user_id].dir | default(ansible_user_id) }}
    file: '{{ bashrc.users[ansible_user_id].file | default(bashrc_file) }}'
    template: '{{ bashrc.users[ansible_user_id].template | default(bashrc_template) }}.j2'

- set_fact:
    line: if [ -f {{ dir }}/{{ file }} ]; then . {{ dir }}/{{ file }}; fi

- name: our dot dir
  file:
    path: '{{ dir }}'
    state: directory

- name: install template
  template:
    src: '{{ template }}'
    dest: '{{ dir }}/{{ file }}'

- name: edit .bashrc
  lineinfile:
    dest: ~/.bashrc
    state: present
    insertafter: EOF
    line: '{{ line }}'
